---
- name: Install required system packages
  package:
    name: "{{ dotfiles_sys_pkgs }}"

- name: Install zsh plugin manager (antibody)
  shell:
    cmd: |
      set pipefail
      curl -sfL git.io/antibody | sh -s - -b /usr/local/bin
    executable: /bin/bash
    creates: /usr/local/bin/antibody
